# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-07 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuestas', '0002_auto_20180604_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='apuestas',
            name='puntos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tarjetas',
            name='puntos',
            field=models.IntegerField(default=0),
        ),
    ]
