# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-18 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuestas', '0004_auto_20180616_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneos',
            name='abierto',
            field=models.BooleanField(default=False),
        ),
    ]
